all:
  children:
    linuxAll:
      children:
        k8sAll:
      vars:
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_private_key_file: /home/neto/.ssh/id_rsa
        ansible_user: server
    k8sAll:
      children:
        k8sMaster:
        k8sWorkers:
    k8sMaster:
      hosts:
        192.168.12.230:
    k8sWorkers:
      hosts:
        192.168.12.231:
        192.168.12.232:
