---
- name: Incluir variáveis de configuração
  include_vars:
    file: "{{ playbook_dir }}/kubernetes/instalação/configuration/cfg.yml"

- name: Debug cfg variable
  debug:
    var: cfg

- name: Usar variáveis de configuração
  debug:
    msg: "O endereço do servidor API é {{ cfg.apiserver_address }} e o CIDR da rede de pods é {{ cfg.pod_network_cidr }}"

- name: Verificar conexão com o nó master
  command: hostname
  delegate_to: "{{ groups['k8sMaster'][0] }}"

- name: Verificar se o kubeadm init já foi executado
  stat:
    path: /etc/kubernetes/admin.conf
  register: kubeadm_init_status

- name: Criar arquivo de configuração do kubeadm
  template:
    src: templates/kubeadm-config.yaml.j2
    dest: /etc/kubernetes/kubeadm-config.yaml
    owner: root
    group: root
    mode: '0644'
  when: "'k8sMaster' in group_names"

- name: Inicializar o kubelet e configurar control-plane
  command: >
    kubeadm init
    --config /etc/kubernetes/kubeadm-config.yaml
  when: "'k8sMaster' in group_names"

- name: Verificar se o arquivo de configuração do kubectl já existe para o usuário atual
  stat:
    path: "/home/{{ ansible_user }}/.kube/config"
  register: kubeconfig_status

- name: Criar a pasta kubeconfig
  file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    mode: '0755'
  when: kubeconfig_status.stat.exists == false

- name: Copiar o arquivo admin.conf
  command: cp /etc/kubernetes/admin.conf /home/{{ ansible_user }}/.kube/config
  when: kubeconfig_status.stat.exists == false

- name: Ajustar permissões do kubeconfig
  command: chown {{ ansible_user }}:{{ ansible_user }} /home/{{ ansible_user }}/.kube/config
  when: kubeconfig_status.stat.exists == false

- name: Mensagem informativa caso o kubeadm init já tenha sido executado
  debug:
    msg: "O cluster Kubernetes já foi inicializado."
  when: kubeadm_init_status.stat.exists == true

- name: Verificar se os pods da rede Weave já estão em execução
  command: kubectl get pods -n kube-system -l app.kubernetes.io/name=weave-net
  register: weave_pods_status
  ignore_errors: yes
  delegate_to: "{{ groups['k8sMaster'][0] }}"
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"

- name: Instalar a rede Weave (pod network)
  command: kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml
  when: "'No resources found' in weave_pods_status.stderr or weave_pods_status.rc != 0"
  delegate_to: "{{ groups['k8sMaster'][0] }}"
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"

- name: Gerar o token de bootstrap para os nós workers
  shell: kubeadm token create --print-join-command
  register: kubeadm_token_output

- name: Salvar o comando join em um arquivo
  copy:
    content: "{{ kubeadm_token_output.stdout }}"
    dest: /etc/kubernetes/join_command.txt

- name: Copiar o comando join do master para a máquina host
  fetch:
    src: /etc/kubernetes/join_command.txt
    dest: ./
    flat: yes

- name: Copiar kubeconfig para a máquina host
  fetch:
    src: "/home/{{ ansible_user }}/.kube/config"
    dest: ./
    flat: yes