- name: Instalar Python3
  ansible.builtin.raw: |
    apt install update
    apt install python3 -y

- name: Update
  ansible.builtin.apt:
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Upgrade
  ansible.builtin.apt:
    upgrade: true
  when: ansible_os_family == "Debian"

- name: Baixar pacotes necessários
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
    state: present
    update_cache: true

- name: Garantir que o diretório /etc/apt/keyrings existe
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Verificar se o arquivo GPG já existe
  ansible.builtin.stat:
    path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  register: gpg_keyring

- name: Baixar a chave GPG para Kubernetes
  ansible.builtin.get_url:
    url: "https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key"
    dest: /tmp/kubernetes-release.key
    mode: '0644'
    owner: root
    group: root
  when: not gpg_keyring.stat.exists

- name: Converter a chave GPG para o formato desarmado
  ansible.builtin.command: "gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-release.key"
  become: true
  when: not gpg_keyring.stat.exists

- name: Criar diretório sources.list.d se não existir
  ansible.builtin.file:
    path: /etc/apt/sources.list.d
    state: directory
    mode: '0755'

- name: Verificar se o arquivo do repositório já existe
  ansible.builtin.stat:
    path: /etc/apt/sources.list.d/kubernetes.list
  register: kubernetes_repo

- name: Adicionar o repositório Kubernetes ao sources.list
  ansible.builtin.copy:
    content: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /'
    dest: /etc/apt/sources.list.d/kubernetes.list
    mode: '0644'
    owner: root
    group: root
  when: not kubernetes_repo.stat.exists

- name: Atualizar índice de pacotes
  ansible.builtin.apt:
    update_cache: true

- name: Instalar kubectl
  ansible.builtin.apt:
    name:
      - kubectl
    state: present
