- name: System requirements
  hosts: k8sAll
  become: true
  roles:
    - k8s-requirements
  tags:
    - k8s-requirements

- name: Containerd Install
  hosts: k8sAll
  become: true
  roles:
    - containerd-install
  tags:
    - containerd-install

- name: Builder cluster
  hosts: k8sMaster
  become: true
  roles:
    - k8s-master
  tags:
    - k8s-master

- name: Ingressar Worker no cluster
  hosts: k8sWorkers
  become: true
  roles:
    - k8s-workers
  tags:
    - k8s-workers

- name: Configurar BastionHost
  hosts: bastionHost
  become: true
  roles:
    - bastion
  tags:
    - bastion

- name: Configurar haproxy
  hosts: haproxy
  become: true
  roles:
    - haproxy
  tags:
    - haproxy

- name: Configurar nfs-server
  hosts: nfsServer
  become: true
  roles:
    - nfs-server
  tags:
    - nfs-server