- name: System requirements
  hosts: k8sAll
  become: true
  roles:
    - k8s-requirements
  tags:
    - k8s-requirements

- name: Instalar Containerd
  hosts: k8sAll
  become: true
  roles:
    - containerd-install
  tags:
    - containerd-install

- name: Configurar o master no cluster
  hosts: k8sMaster
  become: true
  roles:
    - k8s-master
  tags:
    - k8s-master

- name: Ingressar os Workers no cluster
  hosts: k8sWorkers
  become: true
  roles:
    - k8s-workers
  tags:
    - k8s-workers

- name: Configurar BastionHost
  hosts: bastionHost
  become: true
  roles:
    - bastion
  tags:
    - bastion

- name: Configurar haproxy
  hosts: haproxy
  become: true
  roles:
    - haproxy
  tags:
    - haproxy

- name: Configurar nfs-server
  hosts: nfsServer
  become: true
  roles:
    - nfs-server
  tags:
    - nfs-server

- name: Instalar e Configurar Metallb
  hosts: localhost
  become: false
  roles:
    - metallb
  tags:
    - metallb