- name: Update
  ansible.builtin.apt:
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Upgrade
  ansible.builtin.apt:
    upgrade: true
  when: ansible_os_family == "Debian"

- name: Instalar pacotes necessários no Debian/Ubuntu
  ansible.builtin.apt:
    name:
      - nfs-kernel-server
      - nfs-common
    state: present
  when: ansible_os_family == "Debian"

- name: Criar o diretório exportado
  ansible.builtin.file:
    path: /nfs/k8s-storage
    state: directory
    mode: '0777'

- name: Configurar exportação no /etc/exports
  ansible.builtin.lineinfile:
    path: /etc/exports
    line: "/nfs/k8s-storage *(rw,sync,no_subtree_check,no_root_squash)"
    create: true

- name: Exportar os diretórios configurados
  ansible.builtin.command: exportfs -rav

- name: Reiniciar o serviço NFS
  ansible.builtin.service:
    name: nfs-kernel-server
    state: restarted
  when: ansible_os_family == "Debian"
