- name: Update
  ansible.builtin.apt:
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Upgrade
  ansible.builtin.apt:
    upgrade: true
  when: ansible_os_family == "Debian"

- name: Instalar pacote do haproxy
  ansible.builtin.apt:
    name:
      - haproxy
    state: present
    update_cache: true

- name: Enviar arquivo de configuração do HAProxy
  ansible.builtin.template:
    src: templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'

- name: Reiniciar serviço HAProxy
  ansible.builtin.service:
    name: haproxy
    state: restarted
    enabled: true
